GET http://localhost:3012/artists

###

POST http://localhost:3012/artists
{
    "name": "Kanan"
}

###

PUT http://localhost:3012/artists/87 
Content-Type: application/json

{
   "name": "Kanan"
}

###

DELETE http://localhost:3012/artists/87 
Content-Type: application/json

###